### ISSUE TITLE
A question about how you defined internal/external mode in your ipynb code

### ISSUE THREAD

**Issue by Y2KdeLaplace** [veithweilnhammer/predictive_templates#1]
Hello Veith,  
 I have read your predictive template paper. It is so inspiring and now I am trying to learn GLM-HMM for my own data. I am confused about the external/internal index you define:  
`index_ext = np.argmax(np.concatenate(-glmhmm.observations.params)[:,0])  
index_int = np.argmin(np.concatenate(-glmhmm.observations.params)[:,0])`  
 You defined external/internal by comparing weights βs and βh in the paper. Each state has its own β. I read [Ashwood's tutorial](https://github.com/zashwood/ssm/blob/master/notebooks/2b%20Input%20Driven%20Observations%20(GLM-HMM).ipynb) and found that `np.concatenate(-glmhmm.observations.params)` is a num_state*num_input array. These two lines seems to assume that the internal mode is characterized by smaller βs​, while the external mode is characterized by larger βs. Well, from the results, it's correct.
 Was I misunderstanding something or maybe you just fit your model and found all iterations results were similar so you write it that way for convenience?  

Thanks,  
Yiheng

**Comment by veithweilnhammer** [comment]
Hi Yiheng, 

Thanks for your interest in our work. 

We define external versus internal mode based on beta_s, the weight associated with the stimulus, in a glm that predicts choices from the stimulus (beta_s) and the previous experience (beta_h).  Alternatively, you could use the difference between beta_s and beta_h, which will yield the same labeling. Please note that this is just a heuristic to label the states into external and internal. What we were interested in were the differences in behaviour between the two modes.

The parameters fitted by the hmm-glm have a *negative* sign if choices are *attracted* toward the stimulus / the previous experience. This is why there is a negative sign before the parameters in the labeling heuristic: index_ext = np.argmax(-glmhmm.observations.params(:,0)).

I hope this helps! V.

**Comment by Y2KdeLaplace** [comment]
Oh, I got it. This is the first time I learned about [the concept of heuristic](https://stackoverflow.com/questions/2334225/what-is-the-difference-between-a-heuristic-and-an-algorithm)! Thank you Veith
